language: node_js
node_js:
  - "8"

install:
  - npm install -g coveralls
  - npm install
  - npm install graphql@15

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
